export const NUCLEUS_ID = 'N03' as const;
export const SOUL_MESH_PROTOCOL = 'soul-mesh/1' as const;
export const N03_TRANSPORTS = ['mesh-http','event-bus','realtime','edge-function'] as const;
export type N03Transport = typeof N03_TRANSPORTS[number];
export type SoulMeshMessage={protocol:string;id:string;correlationId:string;source:string;target:string;kind:'request'|'response'|'event'|'error'|'ack';capability:string;payload:unknown;timestamp:number|string};
const nuclei=new Set(['N01','N02','N03','N04','N05','N06']);
export function validateMeshMessage(m:SoulMeshMessage){if(m.protocol!==SOUL_MESH_PROTOCOL)throw new Error('UNSUPPORTED_MESH_PROTOCOL');if(!m.id||!m.correlationId)throw new Error('MISSING_MESSAGE_ID');if(!nuclei.has(m.source)||!nuclei.has(m.target)||m.source===m.target)throw new Error('INVALID_NUCLEUS_ROUTE');if(!m.capability&&m.kind!=='event')throw new Error('MISSING_CAPABILITY');if(typeof m.timestamp!=='number'&&typeof m.timestamp!=='string')throw new Error('INVALID_TIMESTAMP');return true}
export function getN03InteroperabilityProfile(){return{nucleus:NUCLEUS_ID,protocol:SOUL_MESH_PROTOCOL,transports:[...N03_TRANSPORTS],peers:['N01','N02','N04','N05','N06'],channels:{inbound:['N01.IN.N03','N02.IN.N03','N04.IN.N03','N05.IN.N03','N06.IN.N03'],outbound:['N03.OUT.N01','N03.OUT.N02','N03.OUT.N04','N03.OUT.N05','N03.OUT.N06']}} as const}
export async function handleMeshMessage(message:SoulMeshMessage,handlers:Record<string,(payload:unknown)=>Promise<unknown>|unknown>){validateMeshMessage(message);if(message.target!==NUCLEUS_ID)throw new Error('WRONG_TARGET');if(message.kind!=='request')return message;const handler=handlers[message.capability];if(!handler)return{...message,kind:'error' as const,payload:{code:'CAPABILITY_NOT_FOUND'}};try{return{...message,kind:'response' as const,payload:await handler(message.payload)}}catch(error){return{...message,kind:'error' as const,payload:{code:'CAPABILITY_EXECUTION_ERROR',detail:error instanceof Error?error.message:'Unknown error'}}}}
