export const NUCLEUS_ID = 'N03' as const;
export const SOUL_MESH_PROTOCOL = 'soul-mesh/1' as const;
export const SOUL_MESH_CONTRACT_VERSION = '1.1.0' as const;
export const SOUL_NUCLEI = ['N01','N02','N03','N04','N05','N06','N07'] as const;
export const SOUL_TRANSPORTS = ['IN_PROCESS','WEBVIEW_BRIDGE','LOOPBACK_HTTP','HTTP','REALTIME'] as const;
export type SoulTransport = typeof SOUL_TRANSPORTS[number];
export const N03_IMPLEMENTED_TRANSPORTS: readonly SoulTransport[] = ['IN_PROCESS','HTTP','REALTIME'];
export const N03_ADAPTER_TARGETS: readonly SoulTransport[] = ['WEBVIEW_BRIDGE','LOOPBACK_HTTP'];
export type SoulMeshMessage={protocol:string;contractVersion?:string;id:string;correlationId:string;source:string;target:string;kind:'request'|'response'|'event'|'error'|'ack';capability:string;payload:unknown;timestamp:string|number;transport?:SoulTransport};
const nuclei=new Set<string>(SOUL_NUCLEI);
export function validateMeshMessage(m:SoulMeshMessage){if(m.protocol!==SOUL_MESH_PROTOCOL)throw new Error('UNSUPPORTED_MESH_PROTOCOL');if(m.contractVersion!==SOUL_MESH_CONTRACT_VERSION)throw new Error('INVALID_CONTRACT_VERSION');if(!m.id||!m.correlationId)throw new Error('MISSING_MESSAGE_ID');if(!nuclei.has(m.source)||!nuclei.has(m.target)||m.source===m.target)throw new Error('INVALID_NUCLEUS_ROUTE');if(!m.capability&&m.kind!=='event')throw new Error('MISSING_CAPABILITY');if(typeof m.timestamp!=='number'&&typeof m.timestamp!=='string')throw new Error('INVALID_TIMESTAMP');if(m.transport&&!SOUL_TRANSPORTS.includes(m.transport))throw new Error('UNSUPPORTED_TRANSPORT');return true}
export function getN03Channels(){return{inbound:['N01.IN.N03','N02.IN.N03','N04.IN.N03','N05.IN.N03','N06.IN.N03'],outbound:['N03.OUT.N01','N03.OUT.N02','N03.OUT.N04','N03.OUT.N05','N03.OUT.N06']} as const}
export function negotiateTransport(offered:readonly SoulTransport[],preferred:readonly SoulTransport[] = ['IN_PROCESS','HTTP','REALTIME','WEBVIEW_BRIDGE','LOOPBACK_HTTP']):SoulTransport|null{for(const transport of preferred)if(offered.includes(transport))return transport;return null}
export function getN03InteroperabilityProfile(){return{nucleus:NUCLEUS_ID,protocol:SOUL_MESH_PROTOCOL,contractVersion:SOUL_MESH_CONTRACT_VERSION,channels:getN03Channels(),referenceTransports:[...SOUL_TRANSPORTS],implementedTransports:[...N03_IMPLEMENTED_TRANSPORTS],adapterTargets:[...N03_ADAPTER_TARGETS]} as const}
export async function handleMeshMessage(message:SoulMeshMessage,handlers:Record<string,(payload:unknown)=>Promise<unknown>|unknown>){validateMeshMessage(message);if(message.target!==NUCLEUS_ID)throw new Error('WRONG_TARGET');if(message.kind!=='request')return message;const handler=handlers[message.capability];if(!handler)return{...message,kind:'error' as const,payload:{code:'CAPABILITY_NOT_FOUND'},contractVersion:SOUL_MESH_CONTRACT_VERSION};try{return{...message,kind:'response' as const,payload:await handler(message.payload),contractVersion:SOUL_MESH_CONTRACT_VERSION}}catch(error){return{...message,kind:'error' as const,payload:{code:'CAPABILITY_EXECUTION_ERROR',detail:error instanceof Error?error.message:'Unknown error'},contractVersion:SOUL_MESH_CONTRACT_VERSION}}}
