// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evzhgfylxuxpxbqmtuha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2emhnZnlseHV4cHhicW10dWhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MDYwODcsImV4cCI6MjA2ODk4MjA4N30.Yymd1gM6LP3Y81D82cziYmlLNXRSZMNof3hEKwFx4xs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});